"use client";

import React, { useState } from 'react';
import Link from 'next/link';
import { Download } from 'lucide-react';
import jsPDF from 'jspdf';

export default function G639Page() {
  const [requestType, setRequestType] = useState<'my' | 'other' | null>('my');
  const [step, setStep] = useState<'form' | 'review'>('form');
  const [formData, setFormData] = useState<Record<string, any>>({});

  const handleFormSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    const formValues = Object.fromEntries(data.entries());
    setFormData({ ...formValues, requestType });
    setStep('review');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(27, 58, 100);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("G-639 Form Summary", 20, 25);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(200, 200, 200);
    doc.text("Generated by Horizon Immigration", 20, 32);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 45, 190, 45);

    // Content
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(11);
    let y = 60;
    
    for (const [key, value] of Object.entries(formData)) {
      const formattedKey = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
      
      doc.setFont("helvetica", "bold");
      doc.text(`${formattedKey}:`, 20, y);
      
      doc.setFont("helvetica", "normal");
      const splitValue = doc.splitTextToSize(String(value || 'Not provided'), 110);
      doc.text(splitValue, 80, y);
      
      y += Math.max(10, splitValue.length * 6 + 4);
      
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: "center" });
    }

    doc.save('G-639-Form.pdf');
  };

  return (
    <main className="min-h-screen bg-[#FDFBF9] py-12 md:py-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-[1200px] mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
        
        {/* Left Column: Information */}
        <div className="lg:col-span-4 space-y-10">
          <div>
            <Link href="/free-tools" className="inline-flex items-center text-[#5A6579] hover:text-[#1B3A64] font-medium mb-6 transition-colors">
              <span className="material-icons text-[18px] mr-2">arrow_back</span>
              Back to Free Tools
            </Link>
            <h1 className="text-4xl font-bold text-[#1B3A64] mb-4 leading-tight">Generate Your FOIA G-639 Request</h1>
            <p className="text-[#5A6579] text-lg leading-relaxed">
              Complete the form below to generate your personalized G-639 FOIA request. We'll create a ready-to-submit PDF with filing instructions.
            </p>
          </div>

          <div className="flex flex-col space-y-4">
            <div className="flex items-start space-x-4">
              <div className="bg-[#EAF1F8] p-3 rounded-full shrink-0">
                <span className="material-icons text-[#1B3A64]">timer</span>
              </div>
              <div>
                <h4 className="font-bold text-[#1B3A64]">10-15 Minutes</h4>
                <p className="text-[#5A6579] text-sm">Simple form completion</p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <div className="bg-[#EAF1F8] p-3 rounded-full shrink-0">
                <span className="material-icons text-[#1B3A64]">picture_as_pdf</span>
              </div>
              <div>
                <h4 className="font-bold text-[#1B3A64]">Instant PDF</h4>
                <p className="text-[#5A6579] text-sm">Ready-to-submit form</p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <div className="bg-[#E2F7F1] p-3 rounded-full shrink-0">
                <span className="material-icons text-[#00B67A]">money_off</span>
              </div>
              <div>
                <h4 className="font-bold text-[#1B3A64]">100% Free</h4>
                <p className="text-[#5A6579] text-sm">No hidden charges</p>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Form */}
        <div className="lg:col-span-8">
          <div className="bg-white rounded-3xl shadow-[0_20px_40px_-15px_rgba(27,58,100,0.08)] border border-gray-100 p-8 md:p-10">
            
            {step === 'form' && (
              <>
                <div className="mb-8 border-b border-gray-100 pb-6">
                  <h2 className="text-2xl font-bold text-[#1B3A64] mb-2">Who's Requesting?</h2>
                  <p className="text-[#5A6579]">Tell us about the person making this request</p>
                </div>

                <form className="space-y-8" onSubmit={handleFormSubmit}>
                  
                  <div className="flex p-1 bg-gray-100 rounded-xl mb-6">
                    <button 
                      type="button" 
                      onClick={() => setRequestType('my')}
                      className={`flex-1 py-3 text-sm font-bold rounded-lg transition-all ${requestType === 'my' ? 'bg-white text-[#1B3A64] shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                      My Records
                    </button>
                    <button 
                      type="button"
                      onClick={() => setRequestType('other')}
                      className={`flex-1 py-3 text-sm font-bold rounded-lg transition-all ${requestType === 'other' ? 'bg-white text-[#1B3A64] shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                      Someone Else's Records
                    </button>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div>
                      <label className="block text-sm font-bold text-[#1B3A64] mb-1.5">First Name *</label>
                      <input name="firstName" required type="text" className="w-full h-12 bg-gray-50 border border-gray-200 rounded-xl px-4 focus:outline-none focus:ring-2 focus:ring-[#1B3A64] focus:bg-white transition-all" />
                    </div>
                    <div>
                      <label className="block text-sm font-bold text-[#1B3A64] mb-1.5">Last Name *</label>
                      <input name="lastName" required type="text" className="w-full h-12 bg-gray-50 border border-gray-200 rounded-xl px-4 focus:outline-none focus:ring-2 focus:ring-[#1B3A64] focus:bg-white transition-all" />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div>
                      <label className="block text-sm font-bold text-[#1B3A64] mb-1.5">Email Address *</label>
                      <input name="email" required type="email" className="w-full h-12 bg-gray-50 border border-gray-200 rounded-xl px-4 focus:outline-none focus:ring-2 focus:ring-[#1B3A64] focus:bg-white transition-all" />
                    </div>
                    <div>
                      <label className="block text-sm font-bold text-[#1B3A64] mb-1.5">Phone Number</label>
                      <input name="phone" type="tel" className="w-full h-12 bg-gray-50 border border-gray-200 rounded-xl px-4 focus:outline-none focus:ring-2 focus:ring-[#1B3A64] focus:bg-white transition-all" />
                    </div>
                  </div>

                  <div>
                    <h3 className="text-lg font-bold text-[#1B3A64] border-b border-gray-100 pb-2 mb-4">Mailing Address</h3>
                    
                    <div className="mb-5">
                      <label className="block text-sm font-bold text-[#1B3A64] mb-1.5">Street Address *</label>
                      <input name="street" required type="text" className="w-full h-12 bg-gray-50 border border-gray-200 rounded-xl px-4 focus:outline-none focus:ring-2 focus:ring-[#1B3A64] focus:bg-white transition-all" />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                      <div className="md:col-span-1">
                        <label className="block text-sm font-bold text-[#1B3A64] mb-1.5">City *</label>
                        <input name="city" required type="text" className="w-full h-12 bg-gray-50 border border-gray-200 rounded-xl px-4 focus:outline-none focus:ring-2 focus:ring-[#1B3A64] focus:bg-white transition-all" />
                      </div>
                      <div className="md:col-span-1">
                        <label className="block text-sm font-bold text-[#1B3A64] mb-1.5">State/Province *</label>
                        <input name="state" required type="text" className="w-full h-12 bg-gray-50 border border-gray-200 rounded-xl px-4 focus:outline-none focus:ring-2 focus:ring-[#1B3A64] focus:bg-white transition-all" />
                      </div>
                      <div className="md:col-span-1">
                        <label className="block text-sm font-bold text-[#1B3A64] mb-1.5">ZIP/Postal Code *</label>
                        <input name="zip" required type="text" className="w-full h-12 bg-gray-50 border border-gray-200 rounded-xl px-4 focus:outline-none focus:ring-2 focus:ring-[#1B3A64] focus:bg-white transition-all" />
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center justify-end pt-6 border-t border-gray-100 mt-8">
                    <button type="submit" className="bg-[#1B3A64] hover:bg-[#0A192F] text-white font-bold px-8 py-3 rounded-xl transition-colors shadow-md flex items-center">
                      Review Information
                      <span className="material-icons ml-1 text-[18px]">arrow_forward</span>
                    </button>
                  </div>
                  
                  <p className="text-xs text-center text-gray-400 mt-4 leading-relaxed">
                    By using this service, you agree to our Terms of Service and Privacy Policy. Your information is secure and only used to generate your FOIA request form.
                  </p>

                </form>
              </>
            )}

            {step === 'review' && (
              <div className="animate-fade-in">
                <button
                  onClick={() => setStep('form')}
                  className="inline-flex items-center text-sm font-semibold text-gray-500 hover:text-[#1B3A64] transition-colors mb-6"
                >
                  <span className="material-icons text-[18px] mr-1">arrow_back</span>
                  Back to Edit Form
                </button>

                <div className="mb-8 border-b border-gray-100 pb-6 text-center">
                  <h2 className="text-2xl font-bold text-[#1B3A64] mb-2">Review Your Information</h2>
                  <p className="text-[#5A6579]">Please double-check your details before generating your G-639 PDF.</p>
                </div>

                <div className="space-y-6">
                  <div className="rounded-xl border border-gray-200 bg-gray-50/50 p-6">
                    <h3 className="text-base font-bold text-[#1B3A64] mb-4 border-b border-gray-200 pb-2">Request Details</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                      <div><span className="text-gray-500 block">Request Type</span><span className="font-medium text-[#1B3A64]">{formData.requestType === 'my' ? 'My Records' : "Someone Else's Records"}</span></div>
                      <div><span className="text-gray-500 block">First Name</span><span className="font-medium text-[#1B3A64]">{formData.firstName || '-'}</span></div>
                      <div><span className="text-gray-500 block">Last Name</span><span className="font-medium text-[#1B3A64]">{formData.lastName || '-'}</span></div>
                      <div><span className="text-gray-500 block">Email Address</span><span className="font-medium text-[#1B3A64]">{formData.email || '-'}</span></div>
                      <div><span className="text-gray-500 block">Phone Number</span><span className="font-medium text-[#1B3A64]">{formData.phone || '-'}</span></div>
                    </div>
                  </div>

                  <div className="rounded-xl border border-gray-200 bg-gray-50/50 p-6">
                    <h3 className="text-base font-bold text-[#1B3A64] mb-4 border-b border-gray-200 pb-2">Mailing Address</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                      <div className="md:col-span-2"><span className="text-gray-500 block">Street Address</span><span className="font-medium text-[#1B3A64]">{formData.street || '-'}</span></div>
                      <div><span className="text-gray-500 block">City</span><span className="font-medium text-[#1B3A64]">{formData.city || '-'}</span></div>
                      <div><span className="text-gray-500 block">State/Province</span><span className="font-medium text-[#1B3A64]">{formData.state || '-'}</span></div>
                      <div><span className="text-gray-500 block">ZIP/Postal Code</span><span className="font-medium text-[#1B3A64]">{formData.zip || '-'}</span></div>
                    </div>
                  </div>
                </div>

                <div className="flex justify-center pt-8">
                  <button
                    onClick={handleDownloadPDF}
                    className="inline-flex items-center justify-center rounded-xl bg-[#1B3A64] text-white h-14 px-10 text-lg font-bold hover:bg-[#0A192F] transition-colors shadow-md w-full md:w-auto"
                  >
                    <Download className="w-5 h-5 mr-3" />
                    Download PDF
                  </button>
                </div>
              </div>
            )}

          </div>
        </div>
      </div>
    </main>
  );
}
